quarkus:
  grpc:
    server:
      use-separate-server: false
    clients:
      demon-client:
        host: localhost
        port: 50052
      hero-client:
        host: localhost
        port: 50051
  http:
    port: 50050
