quarkus:
  grpc:
    server:
      use-separate-server: false
    clients:
      demon-client:
        host: localhost
        port: 50049
      hero-client:
        host: localhost
        port: 50049
      hero-vs-demon-client:
        host: localhost
        port: 50049
  http:
    port: 50050
